theme: jekyll-theme-leap-day
title: Braço Robótico com Arduino
keywords: ARM, Kinematic, IK, FK, Robótica, Braço Robótico, Matrix, Franklin, Teormea, Geoposicionamento, Lei dos Cosenos, ArcTangente, ArcCosseno, ArcSeno, Torque, Kinematic, automação
description: Apresentamos nesta página informações de como construir projetos usando um braço róbotico com duas articulações, além do movimento giratório da Garra e sobre seu próprio eixo.
author: Carlos Delfino {consultoria@carlosdelfino.eti.br}

twitter:
  username: fullsrv
  card: summary

facebook:
  app_id: 351518334888083
  admins: professorcarlosdelfino
  publisher: professorcarlosdelfino
  uselogin: false
  scope: [user_friends, email]
  wellcomemsg: "Olá "

social:
  name: Carlos Delfino
  links:
    - https://twitter.com/fullsrv
    - https://www.facebook.com/CursoArduinoMinas
    - https://www.facebook.com/BasicaoDaEletronica
    - https://www.facebook.com/professorcarlosdelfino
    - https://www.linkedin.com/in/CarlosDelfino
    - https://plus.google.com/+CarlosDelfino
    - https://github.com/CarlosDelfino
    - https://github.com/ArduinoMinas
    - https://keybase.io/carlosdelfino

webmaster_verifications:
  google_site: 5zRTHm8LU2zXC-hlZtBJqy-wiASgu6ER5PbCu67hqcM
  google: google37b3d9124742b7a6
  bing: 7BDB0376D08C31133EDEDA80DC90DFEF

show_downloads: false
repository: ArduinoMinas/ArduinoRobotArm

github:
  zip_url: ""

google_analytics: "UA-21710445-1"

locale: "pt_BR"
lang: "pt_BR"
charset: "utf-8"
encoding: "utf-8"

disqus:
   shortname: arduinorobotarm

plugins: 
 - "jekyll-github-metadata"
 - "jekyll-redirect-from"
 - "jekyll-seo-tag"
 - 'jekyll-feed'
 - 'jekyll-sitemap'
 - 'jekyll-theme-leap-day'
 - "jekyll-remote-theme"
 - "kramdown"
 - "liquid"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/:name/'
    tag: '/tag/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

exclude: 
  - .env
  - .git
  - mobile
  - src
  - Gemfile
  - Gemfile.lock
  - /assets/images/logo.xcf
  - /assets/images/react_redux.xcf